services:
  client:
    build: ./client/my-nuxt-app
    volumes:
      - ./client/my-nuxt-app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "yarn install && yarn dev"

  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/todos?sslmode=disable
    depends_on:
      - db
      - migrate

  db:
    image: postgres:16.4-alpine3.20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: todos
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck: # 追加した
      test: ["CMD-SHELL", "pg_isready -U user -d todos"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    command: ["-path", "/migrations", "-database", "postgres://user:password@db:5432/todos?sslmode=disable", "up"]
    volumes:
      - ./server/db/migrations:/migrations
      - ./wait-for-it.sh:/wait-for-it.sh
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["/wait-for-it.sh", "db:5432", "--", "migrate"]

    # entrypoint: ["sh", "-c", "/wait-for-it.sh db:5432 -- migrate -path /migrations -database postgres://user:password@db:5432/todos?sslmode=disable up"]
    # volumes:
    #  - ./server/db/migrations:/migrations
    # - ./wait-for-it.sh:/wait-for-it.sh

volumes:
  postgres_data: