// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"time"
)

type Todo struct {
	ID        int32     `json:"id"`
	UserID    string    `json:"user_id"`
	Text      string    `json:"text"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID          int32  `json:"id"`
	FirebaseUid string `json:"firebase_uid"`
	Username    string `json:"username"`
	Email       string `json:"email"`
	Password    string `json:"password"`
}
